//! Bounded, short-lived local cache for ChatGPT Web generated-image artifacts.
//!
//! This is the Rust-side landing point of the authenticated byte bridge. The
//! browser extension captures image bytes in the ChatGPT page context and sends
//! them (never a token/cookie/download URL) as a dedicated native-host message;
//! this module stores them in a secure, short-lived, stateless disk cache under
//! the config directory (no shared-memory registry, no schema bump). Web agents
//! reach the cache through the internal `artifact.*` local dispatch, and
//! non-sensitive metadata is exposed through `herdr_inspect` workstation info.
//!
//! Security posture:
//! * directory `0700`, entries `0600`, symlinked cache dirs/entries rejected;
//! * raw payloads are image-only (PNG/JPEG/GIF/WebP) with magic validation;
//! * SHA-256 recomputed in Rust; a browser-supplied digest must match;
//! * conversation/file IDs are validated to a strict, path-safe shape;
//! * deduplicated by `(conversation_id, file_id)` within a short TTL;
//! * bounded artifact count and total bytes under the config dir.

use crate::artifact_import;
use serde_json::{Map, Value, json};
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

pub const RAW_LIMIT_BYTES: usize = 8 * 1024 * 1024;
pub const TTL_SECS: u64 = 15 * 60;
pub const MAX_ARTIFACTS: usize = 32;
pub const MAX_TOTAL_BYTES: usize = 64 * 1024 * 1024;
pub const CACHE_DIR_NAME: &str = "web-artifacts";
const META_SCHEMA: u32 = 1;
const MIN_FILE_ID_LEN: usize = 4;
const MAX_FILE_ID_LEN: usize = 256;
const MAX_CONVERSATION_ID_LEN: usize = 128;

/// Artifact IDs are generated by this runtime as 32 lowercase hex characters.
/// Metadata carrying any other shape is corrupt and must fail closed (it is
/// never a path component, but the strict check keeps every consumer honest).
pub fn validate_artifact_id(value: &str) -> Result<(), String> {
    let valid = value.len() == 32
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte));
    if valid {
        Ok(())
    } else {
        Err("artifact_id must be 32 lowercase hex characters".to_owned())
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CapturedArtifact {
    pub artifact_id: String,
    pub conversation_id: String,
    pub file_id: String,
    pub mime: String,
    pub bytes: usize,
    pub sha256: String,
    pub captured_at: u64,
    pub expires_at: u64,
}

impl CapturedArtifact {
    pub fn metadata_json(&self) -> Value {
        json!({
            "artifact_id": self.artifact_id,
            "conversation_id": self.conversation_id,
            "file_id": self.file_id,
            "mime": self.mime,
            "bytes": self.bytes,
            "sha256": self.sha256,
            "captured_at": self.captured_at,
            "expires_at": self.expires_at,
        })
    }
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/// ChatGPT conversation IDs are opaque base64url-ish identifiers from `/c/<id>`.
/// Accept only path-safe tokens: no separators, whitespace, or control bytes.
pub fn validate_conversation_id(value: &str) -> Result<(), String> {
    if value.is_empty() || value.len() > MAX_CONVERSATION_ID_LEN || !value.bytes().all(is_id_byte) {
        return Err("artifact conversation_id has an invalid shape".to_owned());
    }
    Ok(())
}

/// ChatGPT `sediment://file_<id>` file identifiers. Same path-safe token rules;
/// the download route appends the id to a URL path, so traversal bytes (`/`,
/// `\`, NUL) and reserved delimiters are structurally impossible.
pub fn validate_file_id(value: &str) -> Result<(), String> {
    if value.len() < MIN_FILE_ID_LEN
        || value.len() > MAX_FILE_ID_LEN
        || !value.bytes().all(is_id_byte)
    {
        return Err("artifact file_id has an invalid shape".to_owned());
    }
    Ok(())
}

fn is_id_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.' | b':' | b'=' | b'+')
}

pub fn validate_sha256(value: &str) -> Result<(), String> {
    if value.len() == 64 && value.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        Ok(())
    } else {
        Err("artifact SHA-256 must be 64 hexadecimal characters".to_owned())
    }
}

pub fn image_only_mime(value: &str) -> Result<&'static str, String> {
    let mime = artifact_import::supported_mime(value)
        .ok_or_else(|| format!("unsupported artifact MIME type '{value}'"))?;
    if !artifact_import::is_image_mime(mime) {
        return Err(format!("artifact MIME type '{mime}' is not an image"));
    }
    Ok(mime)
}

// ---------------------------------------------------------------------------
// Cache storage
// ---------------------------------------------------------------------------

/// Resolve the cache directory without creating it. Used by read-only paths.
pub fn cache_dir_if_present(config_dir: &Path) -> Result<Option<PathBuf>, String> {
    let dir = config_dir.join(CACHE_DIR_NAME);
    let Ok(metadata) = fs::symlink_metadata(&dir) else {
        return Ok(None);
    };
    if metadata.file_type().is_symlink() {
        return Err("artifact cache directory must not be a symlink".to_owned());
    }
    if !metadata.is_dir() {
        return Err("artifact cache path is not a directory".to_owned());
    }
    Ok(Some(dir))
}

fn ensure_cache_dir(config_dir: &Path) -> Result<PathBuf, String> {
    let dir = config_dir.join(CACHE_DIR_NAME);
    if let Ok(metadata) = fs::symlink_metadata(&dir) {
        if metadata.file_type().is_symlink() {
            return Err("artifact cache directory must not be a symlink".to_owned());
        }
        if !metadata.is_dir() {
            return Err("artifact cache path is not a directory".to_owned());
        }
        secure_dir(&dir)?;
        return Ok(dir);
    }
    fs::create_dir_all(&dir)
        .map_err(|error| format!("cannot create artifact cache {}: {error}", dir.display()))?;
    secure_dir(&dir)?;
    Ok(dir)
}

#[cfg(unix)]
fn secure_dir(dir: &Path) -> Result<(), String> {
    fs::set_permissions(dir, fs::Permissions::from_mode(0o700))
        .map_err(|error| format!("cannot secure artifact cache {}: {error}", dir.display()))
}

#[cfg(not(unix))]
fn secure_dir(_dir: &Path) -> Result<(), String> {
    Ok(())
}

fn entry_paths(dir: &Path, artifact_id: &str) -> (PathBuf, PathBuf) {
    (
        dir.join(format!("{artifact_id}.bin")),
        dir.join(format!("{artifact_id}.json")),
    )
}

/// Capture and store an image artifact. Idempotent for an already-captured
/// `(conversation_id, file_id)` with identical SHA-256; any other match fails
/// closed with `artifact_digest_conflict`.
pub fn capture(
    config_dir: &Path,
    conversation_id: &str,
    file_id: &str,
    mime: &str,
    raw: &[u8],
    browser_sha256: Option<&str>,
) -> Result<CapturedArtifact, String> {
    validate_conversation_id(conversation_id)?;
    validate_file_id(file_id)?;
    let mime = image_only_mime(mime)?;
    if raw.is_empty() || raw.len() > RAW_LIMIT_BYTES {
        return Err("artifact size is outside the allowed range".to_owned());
    }
    if !artifact_import::magic_matches(mime, raw) {
        return Err("artifact MIME type does not match file signature".to_owned());
    }
    let sha256 = artifact_import::hex_sha256(raw);
    if let Some(expected) = browser_sha256 {
        validate_sha256(expected)?;
        if !expected.eq_ignore_ascii_case(&sha256) {
            return Err("artifact expected digest mismatch".to_owned());
        }
    }

    let dir = ensure_cache_dir(config_dir)?;
    let wall_now = now_millis();
    let existing = scan_entries(&dir)?;
    // `captured_at` is also the eviction order. Multiple browser captures can
    // arrive within the same millisecond, so make it strictly monotonic within
    // this cache instead of relying on wall-clock resolution alone.
    let captured_at = existing
        .iter()
        .map(|(metadata, _)| metadata.captured_at)
        .max()
        .map(|latest| wall_now.max(latest.saturating_add(1)))
        .unwrap_or(wall_now);
    let expires_at = captured_at.saturating_add(TTL_SECS * 1000);

    // Deduplicate by (conversation_id, file_id). A matching digest is idempotent;
    // any other hit for the same pair is a conflict and must fail closed.
    for (metadata, _) in existing {
        if metadata.conversation_id != conversation_id || metadata.file_id != file_id {
            continue;
        }
        if metadata.expires_at <= wall_now {
            let _ = remove_entry(&dir, &metadata.artifact_id);
            continue;
        }
        if metadata.sha256.eq_ignore_ascii_case(&sha256) && metadata.bytes == raw.len() {
            // Refresh the TTL without creating a second entry. A refresh is a
            // new capture event for eviction purposes, so it becomes newest.
            let refreshed = CapturedArtifact {
                artifact_id: metadata.artifact_id.clone(),
                conversation_id: metadata.conversation_id.clone(),
                file_id: metadata.file_id.clone(),
                mime: mime.to_owned(),
                bytes: metadata.bytes,
                sha256: metadata.sha256.clone(),
                captured_at,
                expires_at,
            };
            write_meta(&dir, &refreshed)?;
            return Ok(refreshed);
        }
        return Err("artifact_digest_conflict".to_owned());
    }

    let artifact_id = random_id()?;
    let captured = CapturedArtifact {
        artifact_id,
        conversation_id: conversation_id.to_owned(),
        file_id: file_id.to_owned(),
        mime: mime.to_owned(),
        bytes: raw.len(),
        sha256,
        captured_at,
        expires_at,
    };

    // Bounded cache: prune expired, then evict oldest entries (by capture time)
    // until a new entry fits both the count and total-byte budgets. Eviction is
    // oldest-first so the newest captures survive.
    prune_expired(config_dir)?;
    let mut entries = scan_entries(&dir)?
        .into_iter()
        .map(|(metadata, _)| metadata)
        .collect::<Vec<_>>();
    entries.sort_by_key(|entry| entry.captured_at); // oldest first
    let mut count = entries.len();
    let mut total = entries.iter().map(|entry| entry.bytes).sum::<usize>();
    for entry in entries {
        let over_count = count + 1 > MAX_ARTIFACTS;
        let over_bytes = total.saturating_add(raw.len()) > MAX_TOTAL_BYTES;
        if !over_count && !over_bytes {
            break;
        }
        // Evict this (oldest remaining) entry to make room.
        let _ = remove_entry(&dir, &entry.artifact_id);
        count = count.saturating_sub(1);
        total = total.saturating_sub(entry.bytes);
    }

    write_entry(&dir, &captured, raw)?;
    Ok(captured)
}

fn now_millis() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}

fn random_id() -> Result<String, String> {
    let mut bytes = [0_u8; 16];
    getrandom::fill(&mut bytes).map_err(|error| format!("cannot generate artifact id: {error}"))?;
    Ok(bytes.iter().map(|byte| format!("{byte:02x}")).collect())
}

fn write_entry(dir: &Path, artifact: &CapturedArtifact, raw: &[u8]) -> Result<(), String> {
    write_meta(dir, artifact)?;
    let (bin_path, _) = entry_paths(dir, &artifact.artifact_id);
    let tmp = dir.join(format!("{}.tmp", artifact.artifact_id));
    fs::write(&tmp, raw).map_err(|error| format!("cannot write artifact payload: {error}"))?;
    secure_file(&tmp)?;
    fs::rename(&tmp, &bin_path)
        .map_err(|error| format!("cannot commit artifact payload: {error}"))?;
    Ok(())
}

fn write_meta(dir: &Path, artifact: &CapturedArtifact) -> Result<(), String> {
    let (_, meta_path) = entry_paths(dir, &artifact.artifact_id);
    let tmp = dir.join(format!("{}.meta.tmp", artifact.artifact_id));
    let mut object = Map::new();
    object.insert("schema".to_owned(), json!(META_SCHEMA));
    object.extend(
        artifact
            .metadata_json()
            .as_object()
            .cloned()
            .unwrap_or_default(),
    );
    fs::write(
        &tmp,
        serde_json::to_vec(&Value::Object(object)).unwrap_or_default(),
    )
    .map_err(|error| format!("cannot write artifact metadata: {error}"))?;
    secure_file(&tmp)?;
    fs::rename(&tmp, &meta_path)
        .map_err(|error| format!("cannot commit artifact metadata: {error}"))?;
    Ok(())
}

#[cfg(unix)]
fn secure_file(path: &Path) -> Result<(), String> {
    fs::set_permissions(path, fs::Permissions::from_mode(0o600))
        .map_err(|error| format!("cannot secure artifact file {}: {error}", path.display()))
}

#[cfg(not(unix))]
fn secure_file(_path: &Path) -> Result<(), String> {
    Ok(())
}

fn remove_entry(dir: &Path, artifact_id: &str) -> Result<(), String> {
    let (bin_path, meta_path) = entry_paths(dir, artifact_id);
    let _ = fs::remove_file(&bin_path);
    let _ = fs::remove_file(&meta_path);
    Ok(())
}

fn scan_entries(dir: &Path) -> Result<Vec<(CapturedArtifact, PathBuf)>, String> {
    let mut output = Vec::new();
    let entries =
        fs::read_dir(dir).map_err(|error| format!("cannot scan artifact cache: {error}"))?;
    for entry in entries {
        let entry = entry.map_err(|error| format!("cannot scan artifact cache: {error}"))?;
        let path = entry.path();
        if path.extension().and_then(|value| value.to_str()) != Some("json") {
            continue;
        }
        let Ok(metadata) = fs::symlink_metadata(&path) else {
            continue;
        };
        if metadata.file_type().is_symlink() {
            let _ = fs::remove_file(&path);
            continue;
        }
        let Ok(text) = fs::read_to_string(&path) else {
            let _ = fs::remove_file(&path);
            continue;
        };
        match parse_meta(&text) {
            Ok(Some(artifact)) => output.push((artifact, path)),
            _ => {
                let _ = fs::remove_file(&path);
            }
        }
    }
    Ok(output)
}

fn parse_meta(text: &str) -> Result<Option<CapturedArtifact>, String> {
    let value: Value = serde_json::from_str(text)
        .map_err(|error| format!("invalid artifact metadata: {error}"))?;
    // Schema must match exactly; unknown/corrupt schema fails closed.
    if value.get("schema").and_then(Value::as_u64) != Some(META_SCHEMA as u64) {
        return Ok(None);
    }
    let artifact_id = match value.get("artifact_id").and_then(Value::as_str) {
        Some(value) => value,
        None => return Ok(None),
    };
    if validate_artifact_id(artifact_id).is_err() {
        return Ok(None);
    }
    let conversation_id = match value.get("conversation_id").and_then(Value::as_str) {
        Some(value) => value,
        None => return Ok(None),
    };
    let file_id = match value.get("file_id").and_then(Value::as_str) {
        Some(value) => value,
        None => return Ok(None),
    };
    let mime = match value.get("mime").and_then(Value::as_str) {
        Some(value) => value,
        None => return Ok(None),
    };
    let sha256 = match value.get("sha256").and_then(Value::as_str) {
        Some(value) => value,
        None => return Ok(None),
    };
    let bytes = match value.get("bytes").and_then(Value::as_u64) {
        Some(value) => value as usize,
        None => return Ok(None),
    };
    let captured_at = match value.get("captured_at").and_then(Value::as_u64) {
        Some(value) => value,
        None => return Ok(None),
    };
    let expires_at = match value.get("expires_at").and_then(Value::as_u64) {
        Some(value) => value,
        None => return Ok(None),
    };
    // Strict shape checks: identifiers, image-only MIME, raw byte range, and
    // a sane expiry horizon. Malicious or corrupt metadata fails closed here and
    // is never used to derive a path.
    if validate_conversation_id(conversation_id).is_err()
        || validate_file_id(file_id).is_err()
        || validate_sha256(sha256).is_err()
        || image_only_mime(mime).is_err()
        || bytes == 0
        || bytes > RAW_LIMIT_BYTES
        || expires_at < captured_at
        || expires_at.saturating_sub(captured_at) > TTL_SECS * 1000
    {
        return Ok(None);
    }
    Ok(Some(CapturedArtifact {
        artifact_id: artifact_id.to_owned(),
        conversation_id: conversation_id.to_owned(),
        file_id: file_id.to_owned(),
        mime: mime.to_owned(),
        bytes,
        sha256: sha256.to_owned(),
        captured_at,
        expires_at,
    }))
}

fn find_meta(dir: &Path, artifact_id: &str) -> Result<Option<CapturedArtifact>, String> {
    if validate_artifact_id(artifact_id).is_err() {
        return Ok(None);
    }
    let (_, meta_path) = entry_paths(dir, artifact_id);
    let Ok(file_meta) = fs::symlink_metadata(&meta_path) else {
        return Ok(None);
    };
    if file_meta.file_type().is_symlink() || !file_meta.is_file() {
        return Ok(None);
    }
    let Ok(text) = fs::read_to_string(&meta_path) else {
        return Ok(None);
    };
    parse_meta(&text)
}

fn prune_expired(config_dir: &Path) -> Result<(), String> {
    let Some(dir) = cache_dir_if_present(config_dir)? else {
        return Ok(());
    };
    let now = now_millis();
    for (metadata, _) in scan_entries(&dir)? {
        if metadata.expires_at <= now {
            let _ = remove_entry(&dir, &metadata.artifact_id);
        }
        // Drop entries whose payload file is missing (torn commit or manual tampering).
        let (bin_path, _) = entry_paths(&dir, &metadata.artifact_id);
        if !bin_path.is_file() {
            let _ = remove_entry(&dir, &metadata.artifact_id);
        }
    }
    Ok(())
}

/// Non-sensitive metadata for every live (unexpired, payload-present) artifact.
pub fn list(config_dir: &Path) -> Result<Vec<Value>, String> {
    let Some(dir) = cache_dir_if_present(config_dir)? else {
        return Ok(Vec::new());
    };
    let now = now_millis();
    let mut output = Vec::new();
    for (metadata, _) in scan_entries(&dir)? {
        if metadata.expires_at <= now {
            let _ = remove_entry(&dir, &metadata.artifact_id);
            continue;
        }
        let (bin_path, _) = entry_paths(&dir, &metadata.artifact_id);
        if !bin_path.is_file() {
            let _ = remove_entry(&dir, &metadata.artifact_id);
            continue;
        }
        output.push(metadata.metadata_json());
    }
    output.sort_by_key(|value| value["captured_at"].as_u64().unwrap_or(0));
    Ok(output)
}

/// Read an artifact by ID, revalidating expiry, size, magic, and digest.
/// Returns (metadata, raw payload bytes).
pub fn read(config_dir: &Path, artifact_id: &str) -> Result<(CapturedArtifact, Vec<u8>), String> {
    if validate_artifact_id(artifact_id).is_err() {
        return Err("artifact_not_found".to_owned());
    }
    let Some(dir) = cache_dir_if_present(config_dir)? else {
        return Err("artifact_not_found".to_owned());
    };
    let metadata = find_meta(&dir, artifact_id)?.ok_or_else(|| "artifact_not_found".to_owned())?;
    if metadata.expires_at <= now_millis() {
        let _ = remove_entry(&dir, &metadata.artifact_id);
        return Err("artifact_expired".to_owned());
    }
    let (bin_path, _) = entry_paths(&dir, &metadata.artifact_id);
    if fs::symlink_metadata(&bin_path)
        .map(|meta| meta.file_type().is_symlink())
        .unwrap_or(false)
    {
        let _ = remove_entry(&dir, &metadata.artifact_id);
        return Err("artifact_corrupt".to_owned());
    }
    let raw = fs::read(&bin_path).map_err(|_| "artifact_corrupt".to_owned())?;
    if raw.is_empty() || raw.len() > RAW_LIMIT_BYTES || raw.len() != metadata.bytes {
        let _ = remove_entry(&dir, &metadata.artifact_id);
        return Err("artifact_corrupt".to_owned());
    }
    let sha256 = artifact_import::hex_sha256(&raw);
    if !sha256.eq_ignore_ascii_case(&metadata.sha256) {
        let _ = remove_entry(&dir, &metadata.artifact_id);
        return Err("artifact_corrupt".to_owned());
    }
    if !artifact_import::magic_matches(&metadata.mime, &raw) {
        let _ = remove_entry(&dir, &metadata.artifact_id);
        return Err("artifact_corrupt".to_owned());
    }
    Ok((metadata, raw))
}

/// Remove an artifact entry (used for one-shot consumption after import).
pub fn remove(config_dir: &Path, artifact_id: &str) -> Result<(), String> {
    if validate_artifact_id(artifact_id).is_err() {
        return Ok(());
    }
    let Some(dir) = cache_dir_if_present(config_dir)? else {
        return Ok(());
    };
    remove_entry(&dir, artifact_id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    static NEXT_CACHE_ID: AtomicU64 = AtomicU64::new(0);

    fn temp_config() -> PathBuf {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        std::env::temp_dir().join(format!(
            "herdr-web-artifacts-{}-{}-{nonce:x}",
            std::process::id(),
            NEXT_CACHE_ID.fetch_add(1, Ordering::Relaxed)
        ))
    }

    fn png_bytes() -> Vec<u8> {
        let mut bytes = b"\x89PNG\r\n\x1a\n".to_vec();
        bytes.extend_from_slice(&[1, 2, 3, 4]);
        bytes
    }

    fn jpeg_bytes() -> Vec<u8> {
        let mut bytes = vec![0xff, 0xd8, 0xff, 0xe0];
        bytes.extend_from_slice(&[1, 2, 3]);
        bytes
    }

    #[test]
    fn identifier_validation_is_path_safe_and_bounded() {
        assert!(validate_conversation_id("67b9a1").is_ok());
        assert!(validate_conversation_id(&"a".repeat(128)).is_ok());
        assert!(validate_conversation_id("").is_err());
        assert!(validate_conversation_id(&"a".repeat(129)).is_err());
        assert!(validate_conversation_id("a/b").is_err());
        assert!(validate_conversation_id("a b").is_err());
        assert!(validate_conversation_id("a\u{0}b").is_err());

        assert!(validate_file_id("AbcD-ef01_23").is_ok());
        assert!(validate_file_id("ab").is_err());
        assert!(validate_file_id(&"a".repeat(257)).is_err());
        assert!(validate_file_id("file/../etc").is_err());
        assert!(validate_file_id("file\\x").is_err());
    }

    #[test]
    fn mime_is_forced_to_images_only() {
        assert_eq!(image_only_mime("image/png").unwrap(), "image/png");
        assert_eq!(image_only_mime("image/jpg").unwrap(), "image/jpeg");
        assert_eq!(image_only_mime("image/gif").unwrap(), "image/gif");
        assert_eq!(image_only_mime("image/webp").unwrap(), "image/webp");
        assert!(image_only_mime("text/plain").is_err());
        assert!(image_only_mime("application/octet-stream").is_err());
        assert!(image_only_mime("image/svg+xml").is_err());
        assert!(image_only_mime("").is_err());
    }

    #[test]
    fn capture_round_trips_and_read_revalidates() {
        let config = temp_config();
        let raw = png_bytes();
        let sha = artifact_import::hex_sha256(&raw);
        let captured = capture(
            &config,
            "conv-1",
            "file-abc-123",
            "image/png",
            &raw,
            Some(&sha),
        )
        .unwrap();
        assert_eq!(captured.mime, "image/png");
        assert_eq!(captured.bytes, raw.len());
        assert_eq!(captured.sha256, sha);
        assert_eq!(captured.expires_at - captured.captured_at, TTL_SECS * 1000);

        let (meta, read_raw) = read(&config, &captured.artifact_id).unwrap();
        assert_eq!(meta.artifact_id, captured.artifact_id);
        assert_eq!(read_raw, raw);

        let listed = list(&config).unwrap();
        assert_eq!(listed.len(), 1);
        assert_eq!(listed[0]["file_id"], "file-abc-123");
        assert!(listed[0].get("bytes").is_some());
        assert!(listed[0].get("sha256").is_some());
        assert!(listed[0].get("download_url").is_none());
        assert!(listed[0].get("accessToken").is_none());

        fs::remove_dir_all(&config).unwrap();
    }

    #[test]
    fn capture_is_idempotent_with_matching_digest_and_conflicts_on_mismatch() {
        let config = temp_config();
        let raw = png_bytes();
        let sha = artifact_import::hex_sha256(&raw);
        let first = capture(
            &config,
            "conv-1",
            "file-same-123",
            "image/png",
            &raw,
            Some(&sha),
        )
        .unwrap();
        let second = capture(
            &config,
            "conv-1",
            "file-same-123",
            "image/png",
            &raw,
            Some(&sha),
        )
        .unwrap();
        assert_eq!(first.artifact_id, second.artifact_id);
        assert_eq!(list(&config).unwrap().len(), 1);

        let tampered = {
            let mut bytes = raw.clone();
            bytes.push(0);
            bytes
        };
        let conflict = capture(
            &config,
            "conv-1",
            "file-same-123",
            "image/png",
            &tampered,
            None,
        );
        assert_eq!(conflict.unwrap_err(), "artifact_digest_conflict");

        // A different conversation for the same file id is a distinct artifact.
        let other = capture(
            &config,
            "conv-2",
            "file-same-123",
            "image/png",
            &raw,
            Some(&sha),
        )
        .unwrap();
        assert_ne!(first.artifact_id, other.artifact_id);
        assert_eq!(list(&config).unwrap().len(), 2);

        fs::remove_dir_all(&config).unwrap();
    }

    #[test]
    fn capture_rejects_wrong_mime_magic_missing_digest_and_oversize() {
        let config = temp_config();
        let png = png_bytes();
        let sha = artifact_import::hex_sha256(&png);
        // Declared png but jpeg magic.
        let wrong_magic = capture(
            &config,
            "c1",
            "filex1",
            "image/png",
            &jpeg_bytes(),
            Some(&sha),
        );
        assert_eq!(
            wrong_magic.unwrap_err(),
            "artifact MIME type does not match file signature"
        );
        // Browser digest mismatch fails closed.
        let mismatch = capture(
            &config,
            "c1",
            "filex2",
            "image/png",
            &png,
            Some(&"0".repeat(64)),
        );
        assert_eq!(mismatch.unwrap_err(), "artifact expected digest mismatch");
        // Oversize payload.
        let big = vec![0xff, 0xd8, 0xff, 0xe0];
        assert!(capture(&config, "c1", "filex3", "image/jpeg", &big, None).is_ok());
        assert!(capture(&config, "c1", "filex4", "image/png", &[], None).is_err());
        let exists = capture(&config, "c1", "filex5", "image/png", &png, Some(&sha)).is_ok();
        assert!(exists);
        fs::remove_dir_all(&config).unwrap();
    }

    #[test]
    fn capture_rejects_oversize_payloads() {
        let config = temp_config();
        let mut raw = Vec::with_capacity(RAW_LIMIT_BYTES + 1);
        raw.extend_from_slice(b"\x89PNG\r\n\x1a\n");
        raw.resize(RAW_LIMIT_BYTES + 1, 0);
        let error = capture(&config, "c1", "filebig", "image/png", &raw, None).unwrap_err();
        assert_eq!(error, "artifact size is outside the allowed range");
        let _ = fs::remove_dir_all(&config);
    }

    #[test]
    fn cache_is_bounded_and_prunes_expired_entries() {
        let config = temp_config();
        let png = png_bytes();
        for index in 0..(MAX_ARTIFACTS + 4) {
            capture(
                &config,
                &format!("conv-{index}"),
                &format!("file-{index}"),
                "image/png",
                &png,
                None,
            )
            .unwrap();
        }
        let listed = list(&config).unwrap();
        assert!(listed.len() <= MAX_ARTIFACTS, "bounded artifact count");

        // Expired entries prune on scan.
        let dir = cache_dir_if_present(&config).unwrap().unwrap();
        let entries = scan_entries(&dir).unwrap();
        let first = &entries[0].0;
        let expired = CapturedArtifact {
            expires_at: now_millis().saturating_sub(1000),
            ..first.clone()
        };
        write_meta(&dir, &expired).unwrap();
        let after = list(&config).unwrap();
        assert!(
            !after
                .iter()
                .any(|value| value["artifact_id"] == expired.artifact_id)
        );
        fs::remove_dir_all(&config).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn cache_directory_and_entries_are_private() {
        let config = temp_config();
        let raw = png_bytes();
        capture(&config, "conv-1", "file-mode-1", "image/png", &raw, None).unwrap();
        let dir = cache_dir_if_present(&config).unwrap().unwrap();
        let mode = fs::symlink_metadata(&dir).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o700, "cache dir must be 0700");
        let (bin_path, meta_path) = entry_paths(&dir, &random_id().unwrap());
        drop((bin_path, meta_path));
        let entries = fs::read_dir(&dir).unwrap();
        for entry in entries.flatten() {
            let metadata = fs::symlink_metadata(entry.path()).unwrap();
            assert_eq!(
                metadata.permissions().mode() & 0o777,
                0o600,
                "cache entry {} must be 0600",
                entry.path().display()
            );
        }
        fs::remove_dir_all(&config).unwrap();
    }

    #[test]
    fn read_fails_closed_for_unknown_and_consumed_artifacts() {
        let config = temp_config();
        assert_eq!(
            read(&config, "missing").unwrap_err(),
            "artifact_not_found".to_owned()
        );
        let raw = png_bytes();
        let captured =
            capture(&config, "conv-1", "file-consume-1", "image/png", &raw, None).unwrap();
        remove(&config, &captured.artifact_id).unwrap();
        assert!(read(&config, &captured.artifact_id).is_err());
        assert_eq!(list(&config).unwrap().len(), 0);
        fs::remove_dir_all(&config).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn direct_read_rejects_symlinked_metadata() {
        let config = temp_config();
        let raw = png_bytes();
        let captured =
            capture(&config, "conv-1", "file-meta-link", "image/png", &raw, None).unwrap();
        let dir = cache_dir_if_present(&config).unwrap().unwrap();
        let (_, meta_path) = entry_paths(&dir, &captured.artifact_id);
        let saved_meta = config.join("saved-artifact-meta.json");
        fs::rename(&meta_path, &saved_meta).unwrap();
        std::os::unix::fs::symlink(&saved_meta, &meta_path).unwrap();

        assert_eq!(
            read(&config, &captured.artifact_id).unwrap_err(),
            "artifact_not_found"
        );
        fs::remove_dir_all(&config).unwrap();
    }

    // Each png entry is 5 bytes; MAX_ARTIFACTS is 32 and MAX_TOTAL_BYTES is huge
    // relative to these, so the count bound dominates and eviction must drop
    // the oldest entries while keeping the newest.
    #[test]
    fn eviction_drops_oldest_not_newest_on_count_overflow() {
        let config = temp_config();
        let png = png_bytes();
        let mut captured = Vec::new();
        for index in 0..(MAX_ARTIFACTS + 4) {
            let entry = capture(
                &config,
                &format!("conv-{index}"),
                &format!("file-{index}"),
                "image/png",
                &png,
                None,
            )
            .unwrap();
            captured.push(entry);
        }
        let listed = list(&config).unwrap();
        assert_eq!(listed.len(), MAX_ARTIFACTS, "count bound is enforced");
        // Newest MAX_ARTIFACTS survive; the first 4 (oldest) are evicted.
        let present_ids = listed
            .iter()
            .map(|value| value["artifact_id"].as_str().unwrap().to_owned())
            .collect::<Vec<_>>();
        for entry in captured.iter().take(4) {
            assert!(
                !present_ids.contains(&entry.artifact_id),
                "oldest entry {} must be evicted first",
                entry.artifact_id
            );
        }
        for entry in captured.iter().skip(4) {
            assert!(
                present_ids.contains(&entry.artifact_id),
                "newest entry {} must survive",
                entry.artifact_id
            );
        }
        fs::remove_dir_all(&config).unwrap();
    }

    #[test]
    fn eviction_enforces_total_byte_bound() {
        let config = temp_config();
        // Each entry 3 MiB so the 64 MiB byte cap binds well before the 32-entry
        // count cap (32 x 3 MiB = 96 MiB > 64 MiB), proving the byte budget.
        let mut big = Vec::with_capacity(3 * 1024 * 1024);
        big.extend_from_slice(b"\x89PNG\r\n\x1a\n");
        big.resize(3 * 1024 * 1024, 0);
        for index in 0..40 {
            capture(
                &config,
                &format!("conv-big-{index}"),
                &format!("file-big-{index}"),
                "image/png",
                &big,
                None,
            )
            .unwrap();
        }
        let listed = list(&config).unwrap();
        let total_bytes = listed
            .iter()
            .map(|value| value["bytes"].as_u64().unwrap_or(0))
            .sum::<u64>();
        assert!(total_bytes <= MAX_TOTAL_BYTES as u64, "byte bound enforced");
        // With 3 MiB entries, ~21 fit under 64 MiB, so the count is well below
        // the 32-entry cap — proving byte eviction (not just count) drove this.
        assert!(listed.len() < MAX_ARTIFACTS);
        assert!(!listed.is_empty());
        fs::remove_dir_all(&config).unwrap();
    }

    #[test]
    fn tampered_metadata_fails_closed() {
        let config = temp_config();
        let png = png_bytes();
        let valid = capture(&config, "conv-1", "file-tamper-1", "image/png", &png, None).unwrap();
        let dir = cache_dir_if_present(&config).unwrap().unwrap();
        let (_, meta_path) = entry_paths(&dir, &valid.artifact_id);

        // Corrupt artifact_id (not 32 lowercase hex) must be ignored.
        let bad_id = "../etc/passwd";
        let mut tampered = valid.metadata_json();
        tampered["artifact_id"] = json!(bad_id);
        tampered["schema"] = json!(META_SCHEMA);
        fs::write(&meta_path, serde_json::to_vec(&tampered).unwrap()).unwrap();
        assert!(fs::read_to_string(&meta_path).unwrap().contains(bad_id));
        assert_ne!(
            list(&config).unwrap().len(),
            1,
            "corrupt schema-free meta is dropped"
        );
        // read() with the corrupted (non-hex) id must fail closed, not traverse.
        assert_eq!(read(&config, bad_id).unwrap_err(), "artifact_not_found");

        // Re-seed a valid entry, then tamper the MIME to a non-image type.
        let valid2 = capture(&config, "conv-1", "file-tamper-2", "image/png", &png, None).unwrap();
        let (_, meta2) = entry_paths(&dir, &valid2.artifact_id);
        let mut mime_tamper = valid2.metadata_json();
        mime_tamper["mime"] = json!("text/plain");
        mime_tamper["schema"] = json!(META_SCHEMA);
        fs::write(&meta2, serde_json::to_vec(&mime_tamper).unwrap()).unwrap();
        assert!(
            list(&config)
                .unwrap()
                .iter()
                .all(|value| value["artifact_id"] != valid2.artifact_id),
            "non-image mime metadata must be dropped"
        );
        assert!(read(&config, &valid2.artifact_id).is_err());

        fs::remove_dir_all(&config).unwrap();
    }

    #[test]
    fn artifact_id_validation_is_strict_hex() {
        assert!(validate_artifact_id(&"a".repeat(32)).is_ok());
        assert!(validate_artifact_id(&"A".repeat(32)).is_err()); // uppercase rejected
        let valid = "a".repeat(31) + "b";
        assert!(validate_artifact_id(&valid).is_ok());
        assert!(validate_artifact_id(&"a".repeat(31)).is_err());
        assert!(validate_artifact_id("../etc/passwd").is_err());
        assert!(validate_artifact_id("").is_err());
    }
}
